### ISSUE TITLE
Build failed

### ISSUE THREAD

**Issue by luipir** [boundlessgeo/qgis-testing-environment-docker#1]
this is the log

$> docker build -t qgis-testing-environment --build-arg APT_CATCHER_IP=172.17.0.3 .
Sending build context to Docker daemon 193.5 kB
Step 1 : FROM kartoza/qgis-desktop:2.14.2
 ---> fe93218c9c74
Step 2 : MAINTAINER Alessandro Pasottiapasotti@boundlessgeo.com
 ---> Running in 7824b5644031
 ---> b05011047fa0
Removing intermediate container 7824b5644031
Step 3 : RUN apt-get -y update
 ---> Running in 28051bfaf111
Get:1 http://security.debian.org jessie/updates InRelease [63.1 kB]
Get:2 http://qgis.org wheezy InRelease [3351 B]
Ign http://httpredir.debian.org jessie InRelease
Get:3 http://httpredir.debian.org jessie-updates InRelease [142 kB]
Get:4 http://httpredir.debian.org jessie Release.gpg [2373 B]
Get:5 http://httpredir.debian.org jessie Release [148 kB]
Get:6 http://security.debian.org jessie/updates/main amd64 Packages [313 kB]
Ign http://qgis.org wheezy InRelease
Get:7 http://qgis.org wheezy/main Sources [1151 B]
Get:8 http://httpredir.debian.org jessie-updates/main amd64 Packages [17.3 kB]
Get:9 http://qgis.org wheezy/main amd64 Packages [11.1 kB]
Get:10 http://httpredir.debian.org jessie/main amd64 Packages [9032 kB]
Fetched 9734 kB in 21s (447 kB/s)
Reading package lists...
W: GPG error: http://qgis.org wheezy InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 3FF5FFCAD71472C4
 ---> 4f341419941a
Removing intermediate container 28051bfaf111
Step 4 : RUN apt-get install -y     vim     xvfb     python-pip     python-dev     supervisor     expect-dev
 ---> Running in 30386c46eaaa
Reading package lists...
Building dependency tree...
Reading state information...
python-dev is already the newest version.
xvfb is already the newest version.
The following extra packages will be installed:
  libgpm2 libutempter0 libxv1 libxxf86dga1 python-cffi python-chardet
  python-colorama python-cryptography python-distlib python-html5lib
  python-meld3 python-ndg-httpsclient python-openssl python-ply python-pyasn1
  python-pycparser python-requests python-setuptools python-urllib3
  python-wheel tcl-expect tcl8.6 tk8.6 vim-common vim-runtime x11-utils
  xbitmaps xterm
Suggested packages:
  gpm python-cryptography-doc python-cryptography-vectors python-genshi
  python-lxml python-openssl-doc python-openssl-dbg python-ply-doc doc-base
  tcl-tclreadline ctags vim-doc vim-scripts mesa-utils xfonts-cyrillic
Recommended packages:
  python-dev-all
The following NEW packages will be installed:
  expect libgpm2 libutempter0 libxv1 libxxf86dga1 python-cffi python-chardet
  python-colorama python-cryptography python-distlib python-html5lib
  python-meld3 python-ndg-httpsclient python-openssl python-pip python-ply
  python-pyasn1 python-pycparser python-requests python-setuptools
  python-urllib3 python-wheel supervisor tcl-expect tcl8.6 tk8.6 vim
  vim-common vim-runtime x11-utils xbitmaps xterm
0 upgraded, 32 newly installed, 0 to remove and 32 not upgraded.
Need to get 9376 kB of archives.
After this operation, 40.8 MB of additional disk space will be used.
Get:1 http://httpredir.debian.org/debian/ jessie/main libgpm2 amd64 1.20.4-6.1+b2 [34.0 kB]
Get:2 http://httpredir.debian.org/debian/ jessie/main libxv1 amd64 2:1.0.10-1+b1 [24.0 kB]
Get:3 http://httpredir.debian.org/debian/ jessie/main libxxf86dga1 amd64 2:1.1.4-1+b1 [22.3 kB]
Get:4 http://httpredir.debian.org/debian/ jessie/main vim-common amd64 2:7.4.488-7 [184 kB]
Get:5 http://httpredir.debian.org/debian/ jessie/main tcl-expect amd64 5.45-6 [131 kB]
Get:6 http://httpredir.debian.org/debian/ jessie/main expect amd64 5.45-6 [165 kB]
Get:7 http://httpredir.debian.org/debian/ jessie/main libutempter0 amd64 1.1.5-4 [8020 B]
Get:8 http://httpredir.debian.org/debian/ jessie/main python-ply all 3.4-5 [62.9 kB]
Get:9 http://httpredir.debian.org/debian/ jessie/main python-pycparser all 2.10+dfsg-3 [58.8 kB]
Get:10 http://httpredir.debian.org/debian/ jessie/main python-cffi amd64 0.8.6-1 [67.2 kB]
Get:11 http://httpredir.debian.org/debian/ jessie/main python-chardet all 2.3.0-1 [96.2 kB]
Get:12 http://httpredir.debian.org/debian/ jessie/main python-colorama all 0.3.2-1 [20.3 kB]
Get:13 http://httpredir.debian.org/debian/ jessie/main python-cryptography amd64 0.6.1-1 [165 kB]
Get:14 http://httpredir.debian.org/debian/ jessie/main python-distlib all 0.1.9-1 [113 kB]
Get:15 http://httpredir.debian.org/debian/ jessie/main python-html5lib all 0.999-3 [84.0 kB]
Get:16 http://httpredir.debian.org/debian/ jessie/main python-openssl all 0.14-1 [81.1 kB]
Get:17 http://httpredir.debian.org/debian/ jessie/main python-ndg-httpsclient all 0.3.2-1 [20.5 kB]
Get:18 http://httpredir.debian.org/debian/ jessie/main python-urllib3 all 1.9.1-3 [55.4 kB]
Get:19 http://httpredir.debian.org/debian/ jessie/main python-requests all 2.4.3-6 [204 kB]
Get:20 http://httpredir.debian.org/debian/ jessie/main python-setuptools all 5.5.1-1 [242 kB]
Get:21 http://httpredir.debian.org/debian/ jessie/main python-pip all 1.5.6-5 [114 kB]
Get:22 http://httpredir.debian.org/debian/ jessie/main python-pyasn1 all 0.1.7-1 [49.3 kB]
Get:23 http://httpredir.debian.org/debian/ jessie/main python-wheel all 0.24.0-1 [47.5 kB]
Get:24 http://httpredir.debian.org/debian/ jessie/main tcl8.6 amd64 8.6.2+dfsg-2 [122 kB]
Get:25 http://httpredir.debian.org/debian/ jessie/main tk8.6 amd64 8.6.2-1 [71.1 kB]
Get:26 http://httpredir.debian.org/debian/ jessie/main vim-runtime all 2:7.4.488-7 [5047 kB]
Get:27 http://httpredir.debian.org/debian/ jessie/main vim amd64 2:7.4.488-7 [953 kB]
Get:28 http://httpredir.debian.org/debian/ jessie/main x11-utils amd64 7.7+2 [191 kB]
Get:29 http://httpredir.debian.org/debian/ jessie/main xbitmaps all 1.1.1-2 [32.1 kB]
Get:30 http://httpredir.debian.org/debian/ jessie/main xterm amd64 312-2 [605 kB]
Get:31 http://httpredir.debian.org/debian/ jessie/main python-meld3 amd64 1.0.0-1 [37.0 kB]
Get:32 http://httpredir.debian.org/debian/ jessie/main supervisor all 3.0r1-1 [267 kB]
debconf: delaying package configuration, since apt-utils is not installed
Fetched 9376 kB in 23s (404 kB/s)
Selecting previously unselected package libgpm2:amd64.
(Reading database ... 54136 files and directories currently installed.)
Preparing to unpack .../libgpm2_1.20.4-6.1+b2_amd64.deb ...
Unpacking libgpm2:amd64 (1.20.4-6.1+b2) ...
Selecting previously unselected package libxv1:amd64.
Preparing to unpack .../libxv1_2%3a1.0.10-1+b1_amd64.deb ...
Unpacking libxv1:amd64 (2:1.0.10-1+b1) ...
Selecting previously unselected package libxxf86dga1:amd64.
Preparing to unpack .../libxxf86dga1_2%3a1.1.4-1+b1_amd64.deb ...
Unpacking libxxf86dga1:amd64 (2:1.1.4-1+b1) ...
Selecting previously unselected package vim-common.
Preparing to unpack .../vim-common_2%3a7.4.488-7_amd64.deb ...
Unpacking vim-common (2:7.4.488-7) ...
Selecting previously unselected package tcl-expect:amd64.
Preparing to unpack .../tcl-expect_5.45-6_amd64.deb ...
Unpacking tcl-expect:amd64 (5.45-6) ...
Selecting previously unselected package expect.
Preparing to unpack .../expect_5.45-6_amd64.deb ...
Unpacking expect (5.45-6) ...
Selecting previously unselected package libutempter0.
Preparing to unpack .../libutempter0_1.1.5-4_amd64.deb ...
Unpacking libutempter0 (1.1.5-4) ...
Selecting previously unselected package python-ply.
Preparing to unpack .../python-ply_3.4-5_all.deb ...
Unpacking python-ply (3.4-5) ...
Selecting previously unselected package python-pycparser.
Preparing to unpack .../python-pycparser_2.10+dfsg-3_all.deb ...
Unpacking python-pycparser (2.10+dfsg-3) ...
Selecting previously unselected package python-cffi.
Preparing to unpack .../python-cffi_0.8.6-1_amd64.deb ...
Unpacking python-cffi (0.8.6-1) ...
Selecting previously unselected package python-chardet.
Preparing to unpack .../python-chardet_2.3.0-1_all.deb ...
Unpacking python-chardet (2.3.0-1) ...
Selecting previously unselected package python-colorama.
Preparing to unpack .../python-colorama_0.3.2-1_all.deb ...
Unpacking python-colorama (0.3.2-1) ...
Selecting previously unselected package python-cryptography.
Preparing to unpack .../python-cryptography_0.6.1-1_amd64.deb ...
Unpacking python-cryptography (0.6.1-1) ...
Selecting previously unselected package python-distlib.
Preparing to unpack .../python-distlib_0.1.9-1_all.deb ...
Unpacking python-distlib (0.1.9-1) ...
Selecting previously unselected package python-html5lib.
Preparing to unpack .../python-html5lib_0.999-3_all.deb ...
Unpacking python-html5lib (0.999-3) ...
Selecting previously unselected package python-openssl.
Preparing to unpack .../python-openssl_0.14-1_all.deb ...
Unpacking python-openssl (0.14-1) ...
Selecting previously unselected package python-ndg-httpsclient.
Preparing to unpack .../python-ndg-httpsclient_0.3.2-1_all.deb ...
Unpacking python-ndg-httpsclient (0.3.2-1) ...
Selecting previously unselected package python-urllib3.
Preparing to unpack .../python-urllib3_1.9.1-3_all.deb ...
Unpacking python-urllib3 (1.9.1-3) ...
Selecting previously unselected package python-requests.
Preparing to unpack .../python-requests_2.4.3-6_all.deb ...
Unpacking python-requests (2.4.3-6) ...
Selecting previously unselected package python-setuptools.
Preparing to unpack .../python-setuptools_5.5.1-1_all.deb ...
Unpacking python-setuptools (5.5.1-1) ...
Selecting previously unselected package python-pip.
Preparing to unpack .../python-pip_1.5.6-5_all.deb ...
Unpacking python-pip (1.5.6-5) ...
Selecting previously unselected package python-pyasn1.
Preparing to unpack .../python-pyasn1_0.1.7-1_all.deb ...
Unpacking python-pyasn1 (0.1.7-1) ...
Selecting previously unselected package python-wheel.
Preparing to unpack .../python-wheel_0.24.0-1_all.deb ...
Unpacking python-wheel (0.24.0-1) ...
Selecting previously unselected package tcl8.6.
Preparing to unpack .../tcl8.6_8.6.2+dfsg-2_amd64.deb ...
Unpacking tcl8.6 (8.6.2+dfsg-2) ...
Selecting previously unselected package tk8.6.
Preparing to unpack .../tk8.6_8.6.2-1_amd64.deb ...
Unpacking tk8.6 (8.6.2-1) ...
Selecting previously unselected package vim-runtime.
Preparing to unpack .../vim-runtime_2%3a7.4.488-7_all.deb ...
Adding 'diversion of /usr/share/vim/vim74/doc/help.txt to /usr/share/vim/vim74/doc/help.txt.vim-tiny by vim-runtime'
Adding 'diversion of /usr/share/vim/vim74/doc/tags to /usr/share/vim/vim74/doc/tags.vim-tiny by vim-runtime'
Unpacking vim-runtime (2:7.4.488-7) ...
Selecting previously unselected package vim.
Preparing to unpack .../vim_2%3a7.4.488-7_amd64.deb ...
Unpacking vim (2:7.4.488-7) ...
Selecting previously unselected package x11-utils.
Preparing to unpack .../x11-utils_7.7+2_amd64.deb ...
Unpacking x11-utils (7.7+2) ...
Selecting previously unselected package xbitmaps.
Preparing to unpack .../xbitmaps_1.1.1-2_all.deb ...
Unpacking xbitmaps (1.1.1-2) ...
Selecting previously unselected package xterm.
Preparing to unpack .../archives/xterm_312-2_amd64.deb ...
Unpacking xterm (312-2) ...
Selecting previously unselected package python-meld3.
Preparing to unpack .../python-meld3_1.0.0-1_amd64.deb ...
Unpacking python-meld3 (1.0.0-1) ...
Selecting previously unselected package supervisor.
Preparing to unpack .../supervisor_3.0r1-1_all.deb ...
Unpacking supervisor (3.0r1-1) ...
Processing triggers for mime-support (3.58) ...
Processing triggers for man-db (2.7.0.2-5) ...
Processing triggers for hicolor-icon-theme (0.13-1) ...
Processing triggers for systemd (215-17+deb8u4) ...
Setting up libgpm2:amd64 (1.20.4-6.1+b2) ...
Setting up libxv1:amd64 (2:1.0.10-1+b1) ...
Setting up libxxf86dga1:amd64 (2:1.1.4-1+b1) ...
Setting up vim-common (2:7.4.488-7) ...
Setting up tcl-expect:amd64 (5.45-6) ...
Setting up expect (5.45-6) ...
Setting up libutempter0 (1.1.5-4) ...
Creating utempter group...
Setting up python-ply (3.4-5) ...
Setting up python-pycparser (2.10+dfsg-3) ...
Setting up python-cffi (0.8.6-1) ...
Setting up python-chardet (2.3.0-1) ...
Setting up python-colorama (0.3.2-1) ...
Setting up python-cryptography (0.6.1-1) ...
Setting up python-distlib (0.1.9-1) ...
Setting up python-html5lib (0.999-3) ...
Setting up python-openssl (0.14-1) ...
Setting up python-ndg-httpsclient (0.3.2-1) ...
Setting up python-urllib3 (1.9.1-3) ...
Setting up python-requests (2.4.3-6) ...
Setting up python-setuptools (5.5.1-1) ...
Setting up python-pip (1.5.6-5) ...
Setting up python-pyasn1 (0.1.7-1) ...
Setting up python-wheel (0.24.0-1) ...
Setting up tcl8.6 (8.6.2+dfsg-2) ...
Setting up tk8.6 (8.6.2-1) ...
Setting up vim-runtime (2:7.4.488-7) ...
Processing /usr/share/vim/addons/doc
Setting up vim (2:7.4.488-7) ...
update-alternatives: using /usr/bin/vim.basic to provide /usr/bin/vim (vim) in auto mode
update-alternatives: using /usr/bin/vim.basic to provide /usr/bin/vimdiff (vimdiff) in auto mode
update-alternatives: using /usr/bin/vim.basic to provide /usr/bin/rvim (rvim) in auto mode
update-alternatives: using /usr/bin/vim.basic to provide /usr/bin/rview (rview) in auto mode
update-alternatives: using /usr/bin/vim.basic to provide /usr/bin/vi (vi) in auto mode
update-alternatives: using /usr/bin/vim.basic to provide /usr/bin/view (view) in auto mode
update-alternatives: using /usr/bin/vim.basic to provide /usr/bin/ex (ex) in auto mode
update-alternatives: using /usr/bin/vim.basic to provide /usr/bin/editor (editor) in auto mode
Setting up x11-utils (7.7+2) ...
Setting up xbitmaps (1.1.1-2) ...
Setting up xterm (312-2) ...
update-alternatives: using /usr/bin/xterm to provide /usr/bin/x-terminal-emulator (x-terminal-emulator) in auto mode
update-alternatives: using /usr/bin/lxterm to provide /usr/bin/x-terminal-emulator (x-terminal-emulator) in auto mode
Setting up python-meld3 (1.0.0-1) ...
Setting up supervisor (3.0r1-1) ...
invoke-rc.d: policy-rc.d denied execution of start.
Processing triggers for libc-bin (2.19-18+deb8u4) ...
Processing triggers for python-support (1.0.15) ...
Processing triggers for systemd (215-17+deb8u4) ...
 ---> a9b9ddd8a692
Removing intermediate container 30386c46eaaa
Step 5 : ADD requirements.txt /usr/local/requirements.txt
 ---> 93f663cfe8c9
Removing intermediate container 6feb194a01bb
Step 6 : ADD install.sh /usr/local/bin/install.sh
 ---> 8dc575bdb99b
Removing intermediate container 32543dc2e19d
Step 7 : RUN chmod +x /usr/local/bin/install.sh
 ---> Running in 578e683cd9d2
 ---> c2ad34267b63
Removing intermediate container 578e683cd9d2
Step 8 : RUN /usr/local/bin/install.sh
 ---> Running in 84b73403461e
Downloading/unpacking pep8 (from -r /usr/local/requirements.txt (line 1))
Downloading/unpacking pexpect (from -r /usr/local/requirements.txt (line 2))
Downloading/unpacking subprocess32 (from -r /usr/local/requirements.txt (line 3))
  Running setup.py (path:/tmp/pip-build-hoybmr/subprocess32/setup.py) egg_info for package subprocess32

```
warning: no files found matching '*.h'
no previously-included directories found matching 'build'
no previously-included directories found matching 'dist'
no previously-included directories found matching '.hg*'
```

Downloading/unpacking capturer (from -r /usr/local/requirements.txt (line 4))
  Downloading capturer-2.1.1.tar.gz
  Running setup.py (path:/tmp/pip-build-hoybmr/capturer/setup.py) egg_info for package capturer

Downloading/unpacking ptyprocess>=0.5 (from pexpect->-r /usr/local/requirements.txt (line 2))
  Downloading ptyprocess-0.5.1-py2.py3-none-any.whl
Installing collected packages: pep8, pexpect, subprocess32, capturer, ptyprocess
Compiling /tmp/pip-build-hoybmr/pexpect/pexpect/async.py ...
  File "/tmp/pip-build-hoybmr/pexpect/pexpect/async.py", line 16
    transport, pw = yield from asyncio.get_event_loop()\
                             ^
SyntaxError: invalid syntax

  Running setup.py install for subprocess32
    building '_posixsubprocess' extension
    x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -I/usr/include/python2.7 -c _posixsubprocess.c -o build/temp.linux-x86_64-2.7/_posixsubprocess.o
    x86_64-linux-gnu-gcc -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-z,relro -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -Wl,-z,relro -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security build/temp.linux-x86_64-2.7/_posixsubprocess.o -o build/lib.linux-x86_64-2.7/_posixsubprocess.so

```
warning: no files found matching '*.h'
no previously-included directories found matching 'build'
no previously-included directories found matching 'dist'
no previously-included directories found matching '.hg*'
```

  Running setup.py install for capturer

Successfully installed pep8 pexpect subprocess32 capturer ptyprocess
Cleaning up...
 ---> 367459400565
Removing intermediate container 84b73403461e
Step 9 : ADD qgis_testrunner.py /usr/bin/qgis_testrunner.py
 ---> 2a74b29a9902
Removing intermediate container 12840b3fafed
Step 10 : RUN chmod +x /usr/bin/qgis_testrunner.py
 ---> Running in 0b2363b8196b
 ---> d1e4b42596d7
Removing intermediate container 0b2363b8196b
Step 11 : ADD qgis_testrunner.sh /usr/bin/qgis_testrunner.sh
 ---> c3a2ee63d84c
Removing intermediate container 680c52c908c7
Step 12 : RUN chmod +x /usr/bin/qgis_testrunner.sh
 ---> Running in 7f2ce2ee3892
 ---> 1fb861ef8d45
Removing intermediate container 7f2ce2ee3892
Step 13 : ADD qgis_setup.sh /usr/bin/qgis_setup.sh
 ---> d3b4b93b09d8
Removing intermediate container ee2f6aec6d2b
Step 14 : RUN chmod +x /usr/bin/qgis_setup.sh
 ---> Running in 24ec4dc3e7fd
 ---> 8d5477db2fbb
Removing intermediate container 24ec4dc3e7fd
Step 15 : ADD startup.py /root/.qgis2/python/startup.py
 ---> 31f036be89c2
Removing intermediate container c024931ff6b3
Step 16 : ADD supervisord.conf /etc/supervisor/
 ---> 2ca2a0638a33
Removing intermediate container 7edfe0147d7f
Step 17 : ADD supervisor.xvfb.conf /etc/supervisor/supervisor.d/
 ---> 49ef9d768e8a
Removing intermediate container 7e5691b53c5c
Step 18 : ADD qgis-auth.db /qgis-auth.db
 ---> 3cdd70420bef
Removing intermediate container 8a46ce826317
Step 19 : ENV PYTHONPATH /usr/share/qgis/python/:/usr/lib/python2.7/dist-packages/qgis
 ---> Running in db9ef1fc383a
 ---> 3c067fe35a90
Removing intermediate container db9ef1fc383a
Step 20 : CMD /usr/bin/supervisord -c /etc/supervisor/supervisord.conf
 ---> Running in 3efe3ee214d0
 ---> e7209414186f
Removing intermediate container 3efe3ee214d0
One or more build-args [APT_CATCHER_IP] were not consumed, failing build.

**Comment by luipir** [comment]
rerun the build without --build-arg APT_CATCHER_IP=172.17.0.3 (having the previous images already build), finish build successful

**Comment by elpaso** [comment]
Is that a bug? It's documented in the README
