### ISSUE TITLE
QGIS 2.16 is out

### ISSUE THREAD

**Issue by Gustry** [boundlessgeo/qgis-testing-environment-docker#4]
Hi Alessandro, is-it possible to create a new tag on docker hub for QGIS 2.16 ?
https://hub.docker.com/r/elpaso/qgis-testing-environment/tags/

Thanks

**Comment by elpaso** [comment]
We now have the images hosted on https://hub.docker.com/r/boundlessgeo/qgis-testing-environment/tags/
- release: it's our boundless desktop release, currently based on 2.14
- master_2: current master_2 branch
- master: current master branch (still Qt4 and Py2), we'll swithc to Py3 and Qt5 ASAP

**Comment by Gustry** [comment]
Ok. Will you add 2.16, 2.18 ?

Any risk of difference in our test suite using the boundless desktop release 2.14 ?

We are still using elpaso/qgis-testing-environment:release-2_14 in our tests.

**Comment by elpaso** [comment]
We are now building nightlies (weekly for our `release`) and uploading them here: https://hub.docker.com/r/boundlessgeo/qgis-testing-environment/tags/

Our `release` build is somewhere in between upstream `master_2` and `release-2_14` (it's build from: https://github.com/boundlessgeo/qgis/tree/release-2_14-boundless)

And no: we are not going to add any other build to the mix for now but feel free to do it: the Vagrant file makes it very easy to build on aws an pull to docker hub.

If you are willing to help, I'd really like some help for a new Qt5 Py3 master image.
