### ISSUE TITLE
Error during docker build: Found Proj: 4.9.2.  Cannot build QGIS using Proj older than 4.9.3. 

### ISSUE THREAD

**Issue by elfpkck** [boundlessgeo/qgis-testing-environment-docker#7]
My PC has Ubuntu 20.04 and Docker 19.03.12.

After running [`docker build...`](https://github.com/planetfederal/qgis-testing-environment-docker#building) during QGIS building there is an error:
```
CMake Error at cmake/FindProj.cmake:75 (MESSAGE):
  Found Proj: 4.9.2.  Cannot build QGIS using Proj older than 4.9.3.
Call Stack (most recent call first):
  CMakeLists.txt:330 (FIND_PACKAGE)
```
I've found _libproj-dev_ package for ubuntu 16.04 has version 4.9.2-2 https://packages.ubuntu.com/xenial/amd64/libproj-dev/download but looks like 4.9.3. is needed. So, to get the new version of this package I've tried `FROM ubuntu:18.04` but with no success (some other problem). Then I decided to use older than QGIS3.14 (currently in the master branch) and used `ARG QGIS_BRANCH=release-3_12`, than `release-3_10`, `release-3_8` but there was the same error. `release-3_6` and  `release-3_4` gave another error:
```
CMake Error at CMakeLists.txt:347 (FIND_PACKAGE):
  By not providing "FindQt5SerialPort.cmake" in CMAKE_MODULE_PATH this
  project has asked CMake to find a package configuration file provided by
  "Qt5SerialPort", but CMake did not find one.

  Could not find a package configuration file provided by "Qt5SerialPort"
  with any of the following names:

    Qt5SerialPortConfig.cmake
    qt5serialport-config.cmake

  Add the installation prefix of "Qt5SerialPort" to CMAKE_PREFIX_PATH or set
  "Qt5SerialPort_DIR" to a directory containing one of the above files.  If
  "Qt5SerialPort" provides a separate development package or SDK, be sure it
  has been installed.
```
Finally, `release-3_2` and `release-3_0` were successful.

**Comment by dakcarto** [comment]
Hi @Elfpkck. Thanks for the report.

Please note that the work in this repo by @elpaso was eventually contributed directly to the QGIS project, and is now used in its CI testing. See:
https://github.com/qgis/QGIS/tree/master/.docker

I highly recommend using that project instead of this one. Also, they have pre-built images you can readily use at:
https://hub.docker.com/u/qgis

Closing this issue and looking into archiving this repo.
